config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  get 'home', to: 'home#index'

  # authenticate
  post '/login_or_signup', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # share a video
  resources :sharing_video, only: %i[index create]

  # vote a video
  scope :vote, controller: :vote do
    post :up, as: 'upvote'
    post :down, as: 'downvote'
    post :unvote, as: 'unvote'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  # Associations
  has_many :votes

  # Validations
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }

  def voted?(video_id)
    votes.map(&:video_id).include?(video_id)
  end

  def voted_type(video_id)
    votes.find_by(video_id: video_id)&.kind
  end
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  YT_URL_FORMAT = %r{\A.*(youtu.be/|v/|u/\w/|embed/|watch\?v=|\&v=)([^#\&\?]*).*}i.freeze

  # Associations
  belongs_to :user
  has_many :votes

  # Validations
  validates :url, presence: true, format: YT_URL_FORMAT

  # Hooks
  before_save :get_info_by_url

  def sharer
    user&.email
  end

  private

  def get_info_by_url
    url = Yt::URL.new self.url
    video = Yt::Video.new id: url&.id

    self.uid = video.id
    self.title = video.title
    self.description = video.description
    self.likes = video.like_count
    self.dislikes = video.dislike_count
  rescue Yt::Errors::NoItems
    self.title = ''
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :video

  enum kind: { up_voted: 1, down_voted: 2 }

  validates :user_id, uniqueness: { scope: :video_id }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_action :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:resource_id])
  end

  def logged_in?
    current_user != nil
  end

  def authenticate_user!
    if @current_user.nil?
      flash[:error] = 'You must be signed in to view that page.'
      redirect_to root_url
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @shared_videos = Video.all.order(created_at: :desc)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    authenticate_or_signup!

    redirect_to root_url
  end

  def destroy
    session[:resource_id] = nil
    redirect_to root_url
  end

  private

  def authenticate_or_signup!
    resource = User.find_by_email(resource_params[:email])
    if resource&.authenticate(resource_params[:password])
      session[:resource_id] = resource.id
      flash[:success] = 'Logged In Successfully!!!'
    elsif resource
      # password is invalid
      flash[:error] = 'Invalid Username or Password'
    end

    signup! unless resource
  end

  def signup!
    resource = User.new(resource_params)

    if resource.save
      session[:resource_id] = resource.id
      flash[:success] = 'A account is signup successfully!!!'
    else
      flash[:error] = resource.errors.full_messages
    end
  end

  def resource_params
    params.require(:resource).permit(:email, :password)
  end
end

app/controllers/sharing_video_controller.rb
# frozen_string_literal: true

class SharingVideoController < ApplicationController
  before_action :authenticate_user!

  def index
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    if @video.save
      flash[:success] = 'A video shared successfully!!!'
      redirect_to root_url
    else
      flash[:error] = @video.errors.full_messages
      render :index
    end
  end

  private

  def video_params
    params.require(:video).permit(:url, :user_id)
  end
end

app/controllers/vote_controller.rb
# frozen_string_literal: true

class VoteController < ApplicationController
  before_action :authenticate_user!

  def up
    vote = Vote.new(kind: :up_voted)
    vote.assign_attributes(vote_params)

    if vote.save
      flash[:success] = 'You up-voted a video'
    else
      flash[:error] = vote.errors.full_messages
    end

    redirect_to root_url
  end

  def down
    vote = Vote.new(kind: :down_voted)
    vote.assign_attributes(vote_params)

    if vote.save
      flash[:success] = 'You down-voted a video'
    else
      flash[:error] = vote.errors.full_messages
    end

    redirect_to root_url
  end

  def unvote
    vote = Vote.find_by(user_id: vote_params[:user_id], video_id: vote_params[:video_id])

    if vote&.destroy
      flash[:success] = 'You un-voted a video!!!'
    else
      flash[:error] = 'You have not voted this video yet!!!'
    end

    redirect_to root_url
  end

  private

  def vote_params
    params.require(:vote).permit(:user_id, :video_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # def current_user
  #   @current_user ||= User.find_by(id: session[:resource_id])
  # end

  # def logged_in?
  #   current_user != nil
  # end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/sharing_video_helper.rb
# frozen_string_literal: true

module SharingVideoHelper
end

app/helpers/vote_helper.rb
# frozen_string_literal: true

module VoteHelper
end

app/views/home/_down_voted.html.slim
- action_path = voted ? unvote_path : downvote_path

= button_to action_path, method: :post, class: 'btn border-0', 
            params: { vote: { user_id: @current_user&.id, video_id: video&.id } } do
    - if voted
        i.fas.fa-thumbs-down.fa-3x
    - else
        i.far.fa-thumbs-down.fa-3x

app/views/home/_up_voted.html.slim
- action_path = voted ? unvote_path : upvote_path

= button_to action_path, method: :post, class: 'btn border-0', 
            params: { vote: { user_id: @current_user&.id, video_id: video&.id } } do
    - if voted
        i.fas.fa-thumbs-up.fa-3x
    - else
        i.far.fa-thumbs-up.fa-3x

app/views/home/index.html.slim
- @shared_videos.each do |video|
  .row.justify-content-center.mb-4
    .col.col-md-10
      .media
        .embed-responsive.embed-responsive-16by9.mr-3.w-50
          iframe.embed-responsive-item allowfullscreen="" src="https://www.youtube.com/embed/#{video.uid}" 
        .media-body
          h5.text-danger
            = video.title
          p.mb-0.pd-0.font-weight-light 
            | Shared by:&nbsp
            = video.sharer
          p.font-weight-light
            span.pr-2
              = video.likes
              i.far.fa-thumbs-up.pl-1
            span
              = video.dislikes
              i.far.fa-thumbs-down.pl-1
          p.mb-0.pb-0 Description:
          p.font-weight-bold
            = video.description&.truncate_words(75)

    - if @current_user&.voted?(video&.id)
      .col.col-md-2
        = render partial: "home/#{@current_user.voted_type(video&.id)}", locals: { video: video, voted: true }
    - else
      .col.col-md-1
        = render partial: 'home/up_voted', locals: { video: video, voted: false }
      .col.col-md-1
        = render partial: 'home/down_voted', locals: { video: video, voted: false }

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title MySharedYtvid
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  body
    = render 'shared/header'
    .container.mt-4
      = render 'shared/alert'
      = yield

app/views/shared/_alert.html.slim
.row
    .col-md-12
        - if flash[:error]
            - if flash[:error]&.kind_of?(Array)
                - flash[:error].each do |message|
                    .alert.alert-danger
                        = message
            - else
                .alert.alert-danger
                    = flash[:error]
        - if flash[:success]
            .alert.alert-success.alert-dismissible
                button.close data-dismiss="alert" type="button"  &times;
                = flash[:success]

app/views/shared/_header.html.slim
nav.navbar.navbar-light.navbar-expand-md.shadow-sm.navigation-clean-search
  .container
    = link_to root_path, class: 'navbar-brand' do
      i.fa.fa-home.text-danger
      span.text-danger Funny Movies
    button.navbar-toggler data-target="#navcol-1" data-toggle="collapse" 
      span.sr-only Toggle navigation
      span.navbar-toggler-icon
    #navcol-1.collapse.navbar-collapse.text-right
     - if logged_in?
      = render 'shared/user_info'
     - else
      = render 'shared/login_or_signup_form'

app/views/shared/_login_or_signup_form.html.slim
= form_for :resource, url: login_or_signup_path, html: { class: 'form-inline ml-auto' } do |f|
    .form-group.mb-2
        = f.email_field :email, placeholder: 'Enter email', class: 'form-control'
    .form-group.mx-sm-3.mb-2
        = f.password_field :password, placeholder: 'Enter password', class: 'form-control'
    = f.submit class: 'btn btn-danger mb-2', value: 'Login / Register'

app/views/shared/_user_info.html.slim
form.form-inline.ml-auto
  .form-group.mb-2
    span
      = current_user&.email
  .form-group.mx-sm-3.mb-2
    = link_to 'Share a movie', sharing_video_index_path, class: 'btn btn-danger'
  .form-group.mb-2
    = link_to 'Logout', logout_path, method: :delete, class: 'btn btn-danger'

app/views/sharing_video/_form.html.slim
= form_for @video, url: sharing_video_index_path, method: :post do |f|
    .form-group.row
        label.col-md-2.col-form-label for="ytUrl"  Youtube Url:
        .col-md-10
            = f.text_field :url, id: 'ytUrl', class: 'form-control'
            = f.hidden_field :user_id, value: @current_user&.id
    .form-group.row
        .col-md-10.offset-md-2
            = f.submit class: 'btn btn-danger btn-md btn-block', value: 'Share'

app/views/sharing_video/index.html.slim
.row.justify-content-center
  .col.col-md-8
    .card
      .card-header
        h5.mb-0 Share a Youtube Movie
      .card-body
        = render 'sharing_video/form' 
        